# -*- coding: utf-8 -*-
"""Ass9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Sjsn4jKa96D83RNgA1_4HR4C6hvvxgI
"""

import matplotlib.pyplot as plt
import numpy as np
import math

n=int(10000)
def F(x):
    if(x<=0):
        return 1
    elif(x>0 and x<n):
        return np.exp(-x)
    elif(x>=n):
        return 0
    
X = np.linspace(-20,50,1000)#though n tends to infnity in solution, exp(-x) converges to 0  very fastly!
Y = [F(x) for x in X]

plt.plot(X,Y)
plt.xlabel('$x$')
plt.ylabel('$\lim_{n=\infty}F_{T_{n}}(1-\dfrac{x}{n})$')
plt.title('Cumulative Distribution Function')
plt.grid()
plt.show()